# Generated by Django 3.2 on 2021-10-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211013_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='timepublish',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата пуликации'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Статья'),
        ),
    ]
