# Generated by Django 3.2 on 2021-10-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211013_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['second_name', 'first_name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['timestamp'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('r1', 'Роман'), ('p', 'Поэма'), ('r2', 'Рассказ'), ('s', 'Стих')], default='r1', max_length=2, verbose_name='Жанр'),
        ),
    ]
